### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by AndrianPrakasa** [johndoe31415/startradersdecryptor#1]
Hello, just newbie asking how to run this
I search on google how to run .cpp files but got this error

fatal error: botan/rng.h: No such file or directory
 #include <botan/rng.h>
 
thanks

**Comment by johndoe31415** [comment]
You're missing the Botan headers. If you're on a Debian-ish distro, try "sudo apt-get install libbotan-2-dev" before running "make". Closing this issue.
